language: node_js

env:
  global:
  - SBT_VER=1.1.2

addons:
  homebrew:
    packages:
      - clang-format

matrix:
  include:
   - scala: 2.12.8
     os: osx
     env:
       CMD="checkFormat filesJVM/jacoco filesJS/test plugin/compile filesJVM/travisQuickListReflectionTest filesJVM/allTests"
       TRAVIS_SCALA_VERSION=2.12.8
     osx_image: xcode9.4
     before_install:
       - unset _JAVA_OPTIONS;
       - wget https://github.com/sbt/sbt/releases/download/v1.1.4/sbt-1.1.4.tgz
       - tar -xvf sbt-1.1.4.tgz
       - rm sbt-1.1.4.tgz
       - mv sbt /tmp/sbt
       - npm install -g cmake-js;

   - scala: 2.12.8
     env:
       CMD="filesJVM/jacoco filesJS/test plugin/compile filesJVM/travisQuickListReflectionTest filesJVM/allTests"
       TRAVIS_SCALA_VERSION=2.12.8

   - scala: 2.11.12
     os: osx
     env:
       CMD="filesJVM/jacoco filesJS/test"
       TRAVIS_SCALA_VERSION=2.11.12
     osx_image: xcode9.3

   - scala: 2.11.12
     env:
       CMD="filesJVM/jacoco filesJS/test"
       TRAVIS_SCALA_VERSION=2.11.12

   - scala: 2.10.7
     os: osx
     env:
       CMD="filesJVM/jacoco plugin/compile"
       TRAVIS_SCALA_VERSION=2.10.7
     osx_image: xcode9.3

   - scala: 2.10.7
     env:
       CMD="filesJVM/jacoco plugin/compile"
       TRAVIS_SCALA_VERSION=2.10.7

script: /tmp/sbt/bin/sbt -Dswoval.format=false -Dsbt.version=$SBT_VER -Dswoval.skip.native=true -Dswoval.fork.tests=true -Dswoval.alltests.iterations=20 ++$TRAVIS_SCALA_VERSION $CMD

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS;
  - wget https://github.com/sbt/sbt/releases/download/v1.1.4/sbt-1.1.4.tgz
  - tar -xvf sbt-1.1.4.tgz
  - rm sbt-1.1.4.tgz
  - mv sbt /tmp/sbt
  - npm install -g cmake-js;

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/Library/Caches/Homebrew

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
